-- ============================================================================
-- ADDABAAZ — schema (PostgreSQL 16+)
--
-- Run order:
--   00_create_database.sql   (once, as a superuser)
--   V1__schema.sql           (this file)
--   V2__seed_content.sql     (catalogue migrated from the old index.html)
--   V3__seed_ott.sql         (roles, plans, genres/tags)
--
-- The same files are used by Flyway when the backend starts
-- (spring.flyway.locations=classpath:db/postgresql).
-- ============================================================================

-- ---------------------------------------------------------------------------
-- Users, roles and sessions
-- ---------------------------------------------------------------------------
create table app_user (
    id              uuid primary key default gen_random_uuid(),
    email           varchar(190) not null,
    password_hash   varchar(100),                        -- null for OAuth-only accounts
    full_name       varchar(120),
    phone           varchar(30),
    avatar_url      text,
    auth_provider   varchar(20)  not null default 'LOCAL',   -- LOCAL | GOOGLE
    provider_id     varchar(120),
    email_verified  boolean      not null default false,
    status          varchar(20)  not null default 'ACTIVE',  -- ACTIVE | SUSPENDED | DELETED
    last_login_at   timestamptz,
    created_at      timestamptz  not null default now(),
    updated_at      timestamptz  not null default now()
);

create unique index ux_app_user_email on app_user (lower(email));
create index ix_app_user_provider on app_user (auth_provider, provider_id);

create table role (
    id    smallint generated by default as identity primary key,
    code  varchar(30) not null unique,      -- ROLE_USER | ROLE_ADMIN
    name  varchar(50) not null
);

create table user_role (
    user_id uuid     not null references app_user (id) on delete cascade,
    role_id smallint not null references role (id) on delete cascade,
    primary key (user_id, role_id)
);

-- Refresh tokens are stored (hashed) so they can be revoked and rotated.
create table refresh_token (
    id           uuid primary key default gen_random_uuid(),
    user_id      uuid         not null references app_user (id) on delete cascade,
    token_hash   varchar(128) not null unique,
    family_id    uuid         not null,
    expires_at   timestamptz  not null,
    revoked_at   timestamptz,
    user_agent   varchar(255),
    ip_address   varchar(64),
    created_at   timestamptz  not null default now()
);

create index ix_refresh_token_user on refresh_token (user_id);
create index ix_refresh_token_expires on refresh_token (expires_at);

-- ---------------------------------------------------------------------------
-- OTT: profiles, plans, subscriptions, payments, devices
-- ---------------------------------------------------------------------------
create table user_profile (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid        not null references app_user (id) on delete cascade,
    name       varchar(60) not null,
    avatar_url text,
    is_kids    boolean     not null default false,
    pin        varchar(10),
    is_default boolean     not null default false,
    created_at timestamptz not null default now(),
    unique (user_id, name)
);

create index ix_user_profile_user on user_profile (user_id);

create table plan (
    id           uuid primary key default gen_random_uuid(),
    code         varchar(40) not null unique,
    name         varchar(80) not null,
    description  text,
    price_inr    numeric(10, 2) not null default 0,
    currency     varchar(3)  not null default 'INR',
    duration_days integer    not null default 30,
    max_screens  integer     not null default 1,
    quality      varchar(20) not null default 'HD',      -- SD | HD | FULL_HD | UHD
    active       boolean     not null default true,
    created_at   timestamptz not null default now()
);

create table subscription (
    id          uuid primary key default gen_random_uuid(),
    user_id     uuid        not null references app_user (id) on delete cascade,
    plan_id     uuid        not null references plan (id),
    status      varchar(20) not null default 'ACTIVE',   -- ACTIVE | EXPIRED | CANCELLED | TRIAL
    started_at  timestamptz not null default now(),
    ends_at     timestamptz not null,
    auto_renew  boolean     not null default true,
    cancelled_at timestamptz,
    created_at  timestamptz not null default now()
);

create index ix_subscription_user on subscription (user_id);
create index ix_subscription_ends on subscription (ends_at);

create table payment (
    id                uuid primary key default gen_random_uuid(),
    subscription_id   uuid references subscription (id) on delete set null,
    user_id           uuid not null references app_user (id) on delete cascade,
    amount            numeric(10, 2) not null,
    currency          varchar(3) not null default 'INR',
    gateway           varchar(40),                       -- RAZORPAY | STRIPE | MANUAL
    gateway_reference varchar(120),
    status            varchar(20) not null default 'PENDING',  -- PENDING | PAID | FAILED | REFUNDED
    paid_at           timestamptz,
    created_at        timestamptz not null default now()
);

create index ix_payment_user on payment (user_id);

create table device_session (
    id           uuid primary key default gen_random_uuid(),
    user_id      uuid not null references app_user (id) on delete cascade,
    profile_id   uuid references user_profile (id) on delete set null,
    device_name  varchar(80),
    user_agent   text,
    ip_address   varchar(64),
    last_seen_at timestamptz not null default now(),
    revoked_at   timestamptz,
    created_at   timestamptz not null default now()
);

create index ix_device_session_user on device_session (user_id);

-- ---------------------------------------------------------------------------
-- Catalogue
-- ---------------------------------------------------------------------------
create table show (
    id          uuid primary key default gen_random_uuid(),
    key         varchar(60)  not null unique,   -- 'shahid', 'laughBite', ...
    title       varchar(200) not null,
    subtitle    varchar(200),
    description text,
    image_url   text,
    genre       varchar(80),
    sort_order  integer      not null default 0,
    published   boolean      not null default true,
    created_at  timestamptz  not null default now(),
    updated_at  timestamptz  not null default now()
);

create index ix_show_published on show (published, sort_order);

create table episode (
    id             uuid primary key default gen_random_uuid(),
    show_id        uuid        not null references show (id) on delete cascade,
    external_id    varchar(40),                       -- the old 'v35' style id
    position       integer     not null default 0,
    title          varchar(500) not null,
    youtube_id     varchar(40),
    duration       varchar(10),                       -- 'MM:SS'
    views          bigint      not null default 0,
    thumbnail_url  text,
    availability   varchar(20) not null default 'available',  -- available | unavailable
    episode_no     integer,
    kind           varchar(20) not null default 'EPISODE',    -- EPISODE | PROMO | SPECIAL
    publish_date   timestamptz,
    created_at     timestamptz not null default now(),
    unique (show_id, external_id)
);

create index ix_episode_show on episode (show_id, position);

create table promo_video (
    id            uuid primary key default gen_random_uuid(),
    external_id   varchar(40) unique,
    position      integer     not null default 0,
    title         varchar(500) not null,
    youtube_id    varchar(40),
    duration      varchar(10),
    views         bigint      not null default 0,
    thumbnail_url text,
    availability  varchar(20) not null default 'available',
    kind          varchar(20) not null default 'PROMO',
    publish_date  timestamptz,
    created_at    timestamptz not null default now()
);

create index ix_promo_kind on promo_video (kind, position);

create table poster (
    id         uuid primary key default gen_random_uuid(),
    kind       varchar(20)  not null,          -- UPCOMING | BTS
    folder     varchar(80)  not null,          -- 'UpcomingReleases/' | 'BTS/'
    file_name  varchar(200) not null,
    title      varchar(200),
    badge      varchar(40),
    sort_order integer      not null default 0,
    published  boolean      not null default true,
    created_at timestamptz  not null default now(),
    unique (kind, folder, file_name)
);

create index ix_poster_kind on poster (kind, sort_order);

create table genre (
    id   uuid primary key default gen_random_uuid(),
    name varchar(80) not null unique,
    slug varchar(80) not null unique
);

create table tag (
    id   uuid primary key default gen_random_uuid(),
    name varchar(80) not null unique,
    slug varchar(80) not null unique
);

create table show_genre (
    show_id  uuid not null references show (id) on delete cascade,
    genre_id uuid not null references genre (id) on delete cascade,
    primary key (show_id, genre_id)
);

create table show_tag (
    show_id uuid not null references show (id) on delete cascade,
    tag_id  uuid not null references tag (id) on delete cascade,
    primary key (show_id, tag_id)
);

-- Hero carousel entries. show_id is optional so a banner can promote anything.
create table banner (
    id         uuid primary key default gen_random_uuid(),
    show_id    uuid references show (id) on delete cascade,
    title      varchar(200),
    subtitle   varchar(200),
    image_url  text,
    youtube_id varchar(40),
    cta_label  varchar(40) default 'Watch now',
    sort_order integer     not null default 0,
    active     boolean     not null default true,
    created_at timestamptz not null default now()
);

create index ix_banner_active on banner (active, sort_order);

create table team_member (
    id         uuid primary key default gen_random_uuid(),
    name       varchar(120) not null,
    role       varchar(120),
    image_url  text,
    quote      text,
    sort_order integer      not null default 0,
    published  boolean      not null default true
);

create table service (
    id          uuid primary key default gen_random_uuid(),
    num         varchar(5)  not null,
    title       varchar(120) not null,
    description text,
    sort_order  integer     not null default 0,
    published   boolean     not null default true
);

-- Key/value store for contact details, social links and other site copy.
create table site_setting (
    id         uuid primary key default gen_random_uuid(),
    key        varchar(80) not null unique,
    value      jsonb       not null,
    updated_at timestamptz not null default now()
);

-- ---------------------------------------------------------------------------
-- Engagement
-- ---------------------------------------------------------------------------
create table watchlist (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null references app_user (id) on delete cascade,
    profile_id uuid not null references user_profile (id) on delete cascade,
    show_id    uuid not null references show (id) on delete cascade,
    created_at timestamptz not null default now(),
    unique (profile_id, show_id)
);

create index ix_watchlist_user on watchlist (user_id);

create table playback_progress (
    id               uuid primary key default gen_random_uuid(),
    user_id          uuid not null references app_user (id) on delete cascade,
    profile_id       uuid not null references user_profile (id) on delete cascade,
    episode_id       uuid references episode (id) on delete cascade,
    promo_id         uuid references promo_video (id) on delete cascade,
    position_seconds integer not null default 0,
    duration_seconds integer not null default 0,
    completed        boolean not null default false,
    updated_at       timestamptz not null default now(),
    constraint ck_progress_target check (
        (episode_id is not null and promo_id is null)
        or (episode_id is null and promo_id is not null)
    ),
    unique (profile_id, episode_id),
    unique (profile_id, promo_id)
);

create index ix_progress_profile on playback_progress (profile_id, updated_at desc);

create table watch_history (
    id               uuid primary key default gen_random_uuid(),
    user_id          uuid not null references app_user (id) on delete cascade,
    profile_id       uuid not null references user_profile (id) on delete cascade,
    episode_id       uuid references episode (id) on delete cascade,
    promo_id         uuid references promo_video (id) on delete cascade,
    progress_seconds integer not null default 0,
    watched_at       timestamptz not null default now()
);

create index ix_history_profile on watch_history (profile_id, watched_at desc);

create table rating (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null references app_user (id) on delete cascade,
    show_id    uuid not null references show (id) on delete cascade,
    score      integer not null check (score between 1 and 5),
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now(),
    unique (user_id, show_id)
);

create table review (
    id         uuid primary key default gen_random_uuid(),
    user_id    uuid not null references app_user (id) on delete cascade,
    show_id    uuid not null references show (id) on delete cascade,
    title      varchar(200),
    body       text not null,
    spoiler    boolean not null default false,
    status     varchar(20) not null default 'APPROVED',  -- PENDING | APPROVED | REJECTED
    created_at timestamptz not null default now(),
    updated_at timestamptz not null default now()
);

create index ix_review_show on review (show_id, status, created_at desc);

-- ---------------------------------------------------------------------------
-- Contact form
-- ---------------------------------------------------------------------------
create table contact_inquiry (
    id          uuid primary key default gen_random_uuid(),
    name        varchar(120) not null,
    email       varchar(190) not null,
    phone       varchar(30),
    message     text         not null,
    page        text,
    status      varchar(20)  not null default 'NEW',   -- NEW | READ | ARCHIVED
    ip_address  varchar(64),
    created_at  timestamptz  not null default now()
);

-- Server-side CAPTCHA: the image is rendered by the API, only the hash is kept.
create table captcha_challenge (
    id          uuid primary key default gen_random_uuid(),
    code_hash   varchar(128) not null,
    expires_at  timestamptz  not null,
    consumed_at timestamptz,
    created_at  timestamptz  not null default now()
);

create index ix_captcha_expires on captcha_challenge (expires_at);
